<a href="https://colab.research.google.com/github/Abhinav4518/Abhinav4518/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [2]:
#importing the models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
#Data Collection and PreProcessing
heart_data=pd.read_csv('/content/heart.csv');

In [4]:
#splitting the data into features and target
X=heart_data.drop(columns='target',axis=1)
Y=heart_data['target']

In [5]:
print(X)

      age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0      52    1   0       125   212  ...      0      1.0      2   2     3
1      53    1   0       140   203  ...      1      3.1      0   0     3
2      70    1   0       145   174  ...      1      2.6      0   0     3
3      61    1   0       148   203  ...      0      0.0      2   1     3
4      62    0   0       138   294  ...      0      1.9      1   3     2
...   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
1020   59    1   1       140   221  ...      1      0.0      2   0     2
1021   60    1   0       125   258  ...      1      2.8      1   1     3
1022   47    1   0       110   275  ...      1      1.0      1   1     2
1023   50    0   0       110   254  ...      0      0.0      2   0     2
1024   54    1   0       120   188  ...      0      1.4      1   1     3

[1025 rows x 13 columns]


In [6]:
#Training and Testing Split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=3)


In [7]:
print(X.shape,x_train.shape,x_test.shape)

(1025, 13) (820, 13) (205, 13)


In [8]:
#Comparing the performance of Models
models=[LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [9]:
def compare_models_train_test():
  for model in models:
    model.fit(x_train,y_train)
    test_data_prediction=model.predict(x_test)
    accuracy=accuracy_score(y_test,test_data_prediction)
    print('Accuracy Score of the ', model, '=',accuracy)

In [10]:
compare_models_train_test()

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy Score of the  LogisticRegression() = 0.8390243902439024
Accuracy Score of the  SVC(kernel='linear') = 0.824390243902439
Accuracy Score of the  KNeighborsClassifier() = 0.7560975609756098
Accuracy Score of the  RandomForestClassifier() = 1.0


In [11]:
def compare_models_test_train():
  for model in models:
    model.fit(x_test,y_test)
    train_data_prediction=model.predict(x_train)
    accuracy=accuracy_score(y_train,train_data_prediction)
    print('Accuracy Score of the ', model, '=',accuracy)


compare_models_test_train()

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy Score of the  LogisticRegression() = 0.8268292682926829
Accuracy Score of the  SVC(kernel='linear') = 0.8195121951219512
Accuracy Score of the  KNeighborsClassifier() = 0.6634146341463415
Accuracy Score of the  RandomForestClassifier() = 0.8853658536585366


#Cross Validation

In [13]:
#logistic Regression
cv_score_lr=cross_val_score(LogisticRegression(max_iter=1000),X,Y,cv=5)
print(cv_score_lr)
mean_accuracy_lr=sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy_lr=round(mean_accuracy_lr*100,2)
print(mean_accuracy_lr)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.88292683 0.85853659 0.87804878 0.82439024 0.80487805]
84.98


In [14]:
#Support Vector Classifier
cv_score_svc=cross_val_score(SVC(kernel='linear'),X,Y,cv=5)
print(cv_score_svc)
mean_accuracy_svc=sum(cv_score_svc)/len(cv_score_svc)
mean_accuracy_svc=round(mean_accuracy_svc*100,2)
print(mean_accuracy_svc)

[0.88292683 0.86829268 0.84390244 0.81463415 0.80487805]
84.29


In [15]:
#K-Neighbours
cv_score_kn=cross_val_score(KNeighborsClassifier(),X,Y,cv=5)
print(cv_score_kn)
mean_accuracy_kn=sum(cv_score_kn)/len(cv_score_kn)
mean_accuracy_lr=round(mean_accuracy_kn*100,2)
print(mean_accuracy_kn)

[0.76585366 0.74634146 0.76097561 0.71219512 0.75121951]
0.7473170731707317


In [16]:
#Random Forest
cv_score_rf=cross_val_score(RandomForestClassifier(),X,Y,cv=5)
print(cv_score_rf)
mean_accuracy_rf=sum(cv_score_rf)/len(cv_score_rf)
mean_accuracy_rf=round(mean_accuracy_rf*100,2)
print(mean_accuracy_rf)

[1.         1.         0.98536585 1.         0.98536585]
99.41
