<a href="https://colab.research.google.com/github/Abhinav4518/Abhinav4518/blob/main/Matrix_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Single column and row is known as Vector and more than one column or row is known as Matrix.

In [1]:
import numpy as np

In [2]:
#Creatina a Matrix
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2=np.array([[10,35,45],[50,64,80],[20,15,90]]);
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

In [8]:
#Creating Matrices with Random values
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.15304862 0.43567508 0.8192272 ]
 [0.91332219 0.07932929 0.29812984]
 [0.85088354 0.2525218  0.55977753]]


In [9]:
#Creating with random integers
random_integer_matrix=np.random.randint(100,size=(4,5));
print(random_integer_matrix)

[[65 66 30 72 75]
 [56 10 27 18 50]
 [15 35 45 61 54]
 [ 2 47 94 95 13]]


In [10]:
#Matrix with all values one
matrix_3=np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Integers

In [12]:
matrix_3=np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [14]:
#Null Matrix
null_matrix=np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
#Integer
null_matrix=np.zeros((4,4),dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
#Identity Matrix
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#Transpose of a matrix
a=np.random.randint(100,size=(4,5))
transpose_of_a=np.transpose(a)
print(a)
print(transpose_of_a)

[[31 63 78 62 93]
 [32 90 99 79 69]
 [ 4 80  5 89 32]
 [74 19 52 49 37]]
[[31 32  4 74]
 [63 90 80 19]
 [78 99  5 52]
 [62 79 89 49]
 [93 69 32 37]]
