<a href="https://colab.research.google.com/github/Abhinav4518/Abhinav4518/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy-Numerical Python


Advantage of Numpy Arrays:
1.Allows Several Mathematical operations
2.Faster Operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time Taken by a list

In [3]:
python_list=[i for i in range(100000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.009307752999999863


In [5]:
np_array=np.array( [i for i in range(100000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0005575219999993664


Numpy Arrays

In [6]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
#Creating a 1 dim array
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [12]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [14]:
#create a numpy array of Zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#Create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#Create an array of particular values
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
#Create an identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#Create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.52522099 0.15235118 0.87661587 0.42142508]
 [0.68980087 0.8326786  0.57573102 0.74464325]
 [0.24695205 0.93984284 0.12716155 0.90243585]]


In [21]:
#Create a random array with specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[11 67 16 82 83]
 [68 14 87 15 57]
 [94 27 17 41 89]]


In [22]:
#Array with evenly spaced values--->specifying the number of values required
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [23]:
#array of evenly spaced values--->specifying the steps
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [24]:
#Convert the list to numpy array
list2=[10,20,20,20,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [25]:
c=np.random.randint(10,90,(5,5))
print(c)

[[26 15 25 79 69]
 [81 31 12 69 68]
 [45 88 14 61 11]
 [25 63 84 43 68]
 [70 16 63 81 57]]


In [26]:
#array dimension
print(c.shape)

(5, 5)


In [27]:
#number of dimension
print(c.ndim)

2


In [28]:
#number of elements in an array
print(c.size)

25


In [29]:
#Checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [30]:
list1=[1,2,3,4]
list2=[5,6,7,8]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [35]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[7 6 0]
 [6 4 6]
 [0 4 9]]
[[14 15 12]
 [13 16 17]
 [11 13 13]]
[[21 21 12]
 [19 20 23]
 [11 17 22]]
[[ -7  -9 -12]
 [ -7 -12 -11]
 [-11  -9  -4]]
[[ 98  90   0]
 [ 78  64 102]
 [  0  52 117]]
[[0.5        0.4        0.        ]
 [0.46153846 0.25       0.35294118]
 [0.         0.30769231 0.69230769]]


In [37]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 21 12]
 [19 20 23]
 [11 17 22]]
[[ -7  -9 -12]
 [ -7 -12 -11]
 [-11  -9  -4]]
[[ 98  90   0]
 [ 78  64 102]
 [  0  52 117]]
[[0.5        0.4        0.        ]
 [0.46153846 0.25       0.35294118]
 [0.         0.30769231 0.69230769]]


In [39]:
#Array Manipulation
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 5 6]
 [4 9 5]]
(2, 3)


In [40]:
#Transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[6 4]
 [5 9]
 [6 5]]
(3, 2)


In [41]:
#Another way of finding the transpose
trans2=array.T
print(trans2)
print(trans2.shape)

[[6 4]
 [5 9]
 [6 5]]
(3, 2)


In [43]:
#Reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
b=a.reshape(3,2)
print(b)
print(b.shape)

[[3 6 0]
 [2 8 4]]
(2, 3)
[[3 6]
 [0 2]
 [8 4]]
(3, 2)
